### ISSUE TITLE
"Nari si" next to verbs

### ISSUE THREAD

**Issue by lizardgai4** [horen-lenavi/Horen#19]
According to [this Na'viteri post](https://naviteri.org/2019/08/aawa-lifya-si-lifyavi-amip-a-few-new-words-and-expressions/), "nari si" can be used as an adverb.  "Nari si tengkrr kereynven fìtseng" (Be careful while stepping here) can be shortened to "Nari si keynven!" (step carefully!)

I could not find this quirk in Fwew or Horen.

**Comment by wmannis** [comment]
It is in Plumps' [Annotated Dictionary](https://forum.learnnavi.org/projects/an-annotated-dictionary-(draft)/), and I do think a dictionary is the right place for this. I'll contact Tirea about Fwew.
